cmake_minimum_required(VERSION 3.16)

if(COMMAND idf_component_register)
    idf_component_register(SRCS "two_button_input.c" INCLUDE_DIRS "include")
    target_compile_options(${COMPONENT_LIB} PRIVATE -Wall -Wextra -Werror)
else()
    project(two_button_input LANGUAGES C)
    add_library(two_button_input STATIC two_button_input.c)
    target_include_directories(two_button_input PUBLIC include)
    target_compile_features(two_button_input PUBLIC c_std_11)
    target_compile_options(two_button_input PRIVATE -Wall -Wextra -Werror)
    enable_testing()
    add_executable(two_button_input_test test/two_button_input_test.c)
    target_link_libraries(two_button_input_test PRIVATE two_button_input)
    target_compile_options(two_button_input_test PRIVATE -Wall -Wextra -Werror)
    add_test(NAME two_button_input_test COMMAND two_button_input_test)
endif()
